apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: clusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
