environment: "prod"
branch: ""
deploymentName: "backend-mesh"


replicaCount: 1

image:
  repository: rminz
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m

application:
  INJECT_FAILURE: "0"
  REPLY_DELAY: "0"
  BACKEND_VERSION: "v1"